name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phpstan:
    uses: artemeon/.shared/.github/workflows/phpstan.yml@main
  phpstan-php84:
    uses: artemeon/.shared/.github/workflows/phpstan-php84-upwards.yml
