name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phpunit:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3, 8.2 ]
        stability: [ prefer-stable ]
    name: PHPUnit - PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: php ./vendor/bin/phpunit
